services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./frontend:/app
      - blog-application-frontend-node-modules:/app/node_modules
      - blog-application-frontend-next:/app/.next
    networks:
      - blog-application-frontend-network
    ports:
      - "${EXPOSE_APP_PORT}:3000"
    tty: true

networks:
  blog-application-frontend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.2.0/24

volumes:
  blog-application-frontend-node-modules:
  blog-application-frontend-next:
